fix makefiles

diff --git a/src/mimetype/mod_deps b/src/mimetype/mod_deps
--- a/src/mimetype/mod_deps
+++ b/src/mimetype/mod_deps
@@ -21,53 +21,46 @@
 OPTS=`getopt -o rbehy --long runtime,buildtime,everything,,help -n 'mod_deps' -- "$@"`
 
 if [ $? != 0 ]; then
-   echo "ERROR: Bad option specified."
-   OPTS="--help"
+  echo "ERROR: Bad option specified."
+  OPTS="--help"
 fi
 
 eval set -- "$OPTS"
 
 # if no options then do everything
 if [ "$OPTS" = " --" ]; then
-   EVERYTHING=1
+  EVERYTHING=1
 fi
 
 while true; do
-   case "$1" in
-      -r|--runtime) RUNTIME=1; shift;;
-      -b|--buildtime) BUILDTIME=1; shift;;
-      -e|--everything) EVERYTHING=1; shift;;
-      -y) 
-         YesOpt=" -y "; shift;;      
-      -h|--help)
-         echo "Usage: mod_deps [options]";
-	 echo "  -r or --runtime    : install runtime dependencies"
-	 echo "  -b or --buildtime  : install buildtime dependencies"
-	 echo "  -e or --everything : install all dependencies (default)"
-	 echo "  -h or --help       : this help text"
-	 exit;;
-      --) shift; break;;
-      *) echo "ERROR: option $1 not recognised"; exit 1;;
-   esac
+  case "$1" in
+    -r|--runtime) RUNTIME=1; shift;;
+    -b|--buildtime) BUILDTIME=1; shift;;
+    -e|--everything) EVERYTHING=1; shift;;
+    -y) YesOpt=" -y "; shift;;
+    -h|--help)
+      echo "Usage: mod_deps [options]";
+      echo "  -r or --runtime    : install runtime dependencies"
+      echo "  -b or --buildtime  : install buildtime dependencies"
+      echo "  -e or --everything : install all dependencies (default)"
+      echo "  -h or --help       : this help text"
+      exit;;
+    --) shift; break;;
+    *) echo "ERROR: option $1 not recognised"; exit 1;;
+  esac
 done
 
-# This must run as root.
-if [ `id -u` != "0" ] ; then
-   echo "ERROR: fo-installdeps must run as root."
-   echo "Aborting."
-   exit 1
-fi
-
-if [ $EVERYTHING ]; then
-   echo "*** Installing both runtime and buildtime dependencies ***"
-   RUNTIME=1
-   BUILDTIME=1
-fi
 # This must run as root.
 if [ `id -u` != "0" ] ; then
   echo "ERROR: fo-installdeps must run as root."
   echo "Aborting."
   exit 1
+fi
+
+if [ $EVERYTHING ]; then
+  echo "*** Installing both runtime and buildtime dependencies ***"
+  RUNTIME=1
+  BUILDTIME=1
 fi
 
 # figure out what distro we're on
@@ -88,7 +81,15 @@ if [ $BUILDTIME ]; then
   case "$DISTRO" in
     Debian|Ubuntu|LinuxMint)
       apt-get $YesOpt install \
-      libmagic-dev;;
+        libmagic-dev
+      ;;
+    RedHatEnterprise*|CentOS|Fedora)
+      if [ $YesOpt ]; then
+        YesOpt='-y'
+      fi
+      yum $YesOpt install \
+        file-devel
+      ;;
   esac
 fi
 
@@ -97,19 +98,15 @@ if [ $RUNTIME ]; then
   case "$DISTRO" in
     Debian|Ubuntu|LinuxMint)
       apt-get $YesOpt install \
-      libmagic1;;
-    RedHatEnterprise*|CentOS)
+        libmagic1
+      ;;
+    RedHatEnterprise*|CentOS|Fedora)
       if [ $YesOpt ]; then
         YesOpt='-y'
-      fi        
+      fi
       yum $YesOpt install \
-        file-libs;;
-    Fedora)
-      if [ $YesOpt ]; then
-        YesOpt='-y'
-      fi        
-      yum $YesOpt install \
-        file-libs;;
+        file-libs
+      ;;
   esac
 fi
 
