don't exit if we can't remove the db, use a better method for ensuring nobody is using the db before removing
git-svn-id: http://svn.code.sf.net/p/fossology/code/trunk@1683 a5643f74-2041-0410-a2b9-94ffef304a07

diff --git a/fossology/utils/fo-cleanold b/fossology/utils/fo-cleanold
--- a/fossology/utils/fo-cleanold
+++ b/fossology/utils/fo-cleanold
@@ -176,23 +176,22 @@ if [ $RMDB ]; then
    # first check that the db is running
    su postgres -c 'echo \\q|psql'
    if [ $? != 0 ]; then
-      echo "ERROR: postgresql isn't running"
-      exit 1
-   fi
-
-   # and next that the db exists
-   su postgres -c 'psql -l' |grep -q fossology
-   if [ $? = 0 ]; then
-      echo "*** Deleting database ***"
-      # restart the db to ensure it's not in use
-      /etc/init.d/postgresql* restart
-      su postgres -c 'echo "drop database fossology"|psql'
-      if [ $? != 0 ]; then
-         echo "ERROR: failed to delete database"
-         exit 1
-      fi
+      echo "ERROR: postgresql isn't running, not deleting database"
    else
-      echo "NOTE: fossology database does not exist, so not deleting"
+      # and next that the db exists
+      su postgres -c 'psql -l' |grep -q fossology
+      if [ $? = 0 ]; then
+         echo "*** Deleting database ***"
+         # stop all users of the fossology db
+         pkill -f -u postgres fossy || true
+         su postgres -c 'echo "drop database fossology"|psql'
+         if [ $? != 0 ]; then
+            echo "ERROR: failed to delete database"
+            exit 1
+         fi
+      else
+         echo "NOTE: fossology database does not exist, not deleting"
+      fi
    fi
 fi
 
