The 2nd version about install dependencies, welcome your comments. Note: if the dependency is related to the codename of one distro, you should install them respectively, E.g. lenny|hardy) apt-get install postgresql-server-dev-8.3;; squeeze) apt-get install postgresql-server-dev-8.4;;
git-svn-id: http://svn.code.sf.net/p/fossology/code/branches/fossology2.0/fossology@5136 a5643f74-2041-0410-a2b9-94ffef304a07

diff --git a/src/wget_agent/mod_deps b/src/wget_agent/mod_deps
--- a/src/wget_agent/mod_deps
+++ b/src/wget_agent/mod_deps
@@ -1,1 +1,39 @@
-wget
+#!/bin/bash
+# FOSSology mod_deps script
+#
+# Copyright (C) 2011 Hewlett-Packard Development Company, L.P.
+# This script helps you install dependencies on a system. for a module
+
+# This must run as root.
+if [ `id -u` != "0" ] ; then
+  echo "ERROR: fo-installdeps must run as root."
+  echo "Aborting."
+  exit 1
+fi
+
+# figure out what distro we're on
+DISTRO=`lsb_release -is`
+CODENAME=`lsb_release -cs`
+
+if [ "$?" != "0" ]; then
+  echo "ERROR: this program requires the lsb_release command. On Debian based"
+  echo "  systems this is probably in the lsb-release package, on"
+  echo "  Fedora/RedHat systems it is probably the redhat-lsb package."
+  exit 1
+fi
+
+########################################################################
+
+case "$DISTRO" in
+  Debian|Ubuntu|LinuxMint)
+    apt-get install \
+      wget;;
+  RedHatEnterprise*|CentOS)
+    yum install \
+      wget;;
+  Fedora)
+    yum install \
+      wget;;
+esac
+
+#######################################################################
