move dbcheck from db postinst to agent postinst, install Db.conf 660, then chgrp fossy in postinst
git-svn-id: http://svn.code.sf.net/p/fossology/code/trunk@1740 a5643f74-2041-0410-a2b9-94ffef304a07

diff --git a/fossology/common/fo-postinstall.in b/fossology/common/fo-postinstall.in
--- a/fossology/common/fo-postinstall.in
+++ b/fossology/common/fo-postinstall.in
@@ -204,6 +204,32 @@ if [ $AGENT ]; then
       echo "  in $REPO and are {$PROJECTUSER}:{$PROJECTGROUP} and 2770."
    fi
 
+   ## check that the db is accessable
+   echo "*** Checking database connectivity ***"
+   DBCONF="{$SYSCONFDIR}/fossology/Db.conf"
+   if [ ! -f $DBCONF ]; then
+      echo "ERROR: missing $DBCONF, cannot proceed."
+   fi
+
+   # make install sets Db.conf's mode to 660, but can't chgrp it because
+   # the group doesn't exist until we create it above. So chgrp now
+   chgrp {$PROJECTGROUP} $DBCONF || echo "ERROR: failed to chgrp $DBCONF"
+
+   # check that we can talk to the db
+   if [ -x {$LIBEXECDIR}/dbcheck ]; then
+      {$LIBEXECDIR}/dbcheck
+   else
+      echo "ERROR: no {$LIBEXECDIR}/dbcheck, have you installed?"
+      exit 1
+   fi
+   if [ $? != 0 ]; then
+      echo "ERROR: unable to connect to database, please check {$SYSCONFDIR}/fossology/Db.conf"
+      exit 1
+   else
+      echo "NOTE: Connect succeeded, database is working."
+   fi
+
+
    ## Initialize the tables, License.bsam, and other setup done by fossinit
    # In multi-system installs the database machine must be installed first
    # in order for this to work on other machines.
diff --git a/fossology/db/dbcreate.in b/fossology/db/dbcreate.in
--- a/fossology/db/dbcreate.in
+++ b/fossology/db/dbcreate.in
@@ -7,8 +7,6 @@
 
 echo "*** Setting up the FOSSology database ***"
 
-DBCONF="{$SYSCONFDIR}/fossology/Db.conf"
-
 # At some point this is where we could dynamically set the db password
 
 # first check that postgres is running
@@ -22,29 +20,15 @@ fi
 su postgres -c 'psql -l' |grep -q fossology
 if [ $? = 0 ]; then
    echo "NOTE: fossology database already exists, not creating"
-   echo "*** Checking database connectivity ***"
-   # check that we can talk to the db
-   if [ -x {$LIBEXECDIR}/dbcheck ]; then
-      {$LIBEXECDIR}/dbcheck
+   echo "*** Checking for plpgsql support ***"
+   su postgres -c 'createlang -l fossology' |grep -q plpgsql
+   if [ $? = 0 ]; then
+      echo "NOTE: plpgsql already exists in fossology database, good"
    else
-      echo "ERROR: no {$LIBEXECDIR}/dbcheck, have you installed?"
-      exit 1
-   fi
-   if [ $? != 0 ]; then
-      echo "ERROR: unable to connect to database, please check $DBCONF"
-      exit 1
-   else
-      echo "NOTE: Connect succeeded, database is working."
-      echo "*** Checking for plpgsql support ***"
-      su postgres -c 'createlang -l fossology' |grep -q plpgsql
-      if [ $? = 0 ]; then
-         echo "NOTE: plpgsql already exists in fossology database, good"
-      else
-         echo "NOTE: plpgsql doesn't exist, adding"
-         su postgres -c 'createlang plpgsql fossology'
-         if [ $? != 0 ]; then
-            echo "ERROR: failed to add plpgsql to fossology database"
-         fi
+      echo "NOTE: plpgsql doesn't exist, adding"
+      su postgres -c 'createlang plpgsql fossology'
+      if [ $? != 0 ]; then
+         echo "ERROR: failed to add plpgsql to fossology database"
       fi
    fi
 else
