remove init.ui semaphore until we figure out how to fix it, fix some indenting
git-svn-id: http://svn.code.sf.net/p/fossology/code/trunk@1605 a5643f74-2041-0410-a2b9-94ffef304a07

diff --git a/fossology/common/fo-postinstall.in b/fossology/common/fo-postinstall.in
--- a/fossology/common/fo-postinstall.in
+++ b/fossology/common/fo-postinstall.in
@@ -79,56 +79,56 @@ fi
 ########################################################################
 
 if [ $DATABASE ]; then
-echo "*** Setting up database ***"
+   echo "*** Setting up database ***"
 
-DBCONF="{$SYSCONFDIR}/fossology/Db.conf"
+   DBCONF="{$SYSCONFDIR}/fossology/Db.conf"
 
-# At some point this is where we could dynamically set the db password
+   # At some point this is where we could dynamically set the db password
 
-# first check that postgres is running
-su postgres -c 'echo \\q|psql'
-if [ $? != 0 ]; then
-   echo "ERROR: postgresql isn't running"
-   exit 1
-fi
-
-# then check to see if the db already exists
-su postgres -c 'psql -l' |grep -q fossology
-if [ $? = 0 ]; then
-   echo "NOTE: fossology database already exists, not creating"
-   echo "*** Checking database connectivity ***"
-   # check that we can talk to the db
-   if [ -x {$AGENTTESTDDIR}/dbcheck ]; then
-      {$AGENTTESTDDIR}/dbcheck
-   else
-      echo "ERROR: no {$AGENTTESTDDIR}/dbcheck, have you installed?"
+   # first check that postgres is running
+   su postgres -c 'echo \\q|psql'
+   if [ $? != 0 ]; then
+      echo "ERROR: postgresql isn't running"
       exit 1
    fi
-   if [ $? != 0 ]; then
-      echo "ERROR: unable to connect to database, please check $DBCONF"
-      exit 1
-   else
-      echo "NOTE: Connect succeeded, database is working."
-      echo "*** Checking for plpgsql support ***"
-      su postgres -c 'createlang -l fossology' |grep -q plpgsql
-      if [ $? = 0 ]; then
-         echo "NOTE: plpgsql already exists in fossology database, good"
+
+   # then check to see if the db already exists
+   su postgres -c 'psql -l' |grep -q fossology
+   if [ $? = 0 ]; then
+      echo "NOTE: fossology database already exists, not creating"
+      echo "*** Checking database connectivity ***"
+      # check that we can talk to the db
+      if [ -x {$AGENTTESTDDIR}/dbcheck ]; then
+         {$AGENTTESTDDIR}/dbcheck
       else
-         echo "NOTE: plpgsql doesn't exist, adding"
-         su postgres -c 'createlang plpgsql fossology'
-         if [ $? != 0 ]; then
-            echo "ERROR: failed to add plpgsql to fossology database"
+         echo "ERROR: no {$AGENTTESTDDIR}/dbcheck, have you installed?"
+         exit 1
+      fi
+      if [ $? != 0 ]; then
+         echo "ERROR: unable to connect to database, please check $DBCONF"
+         exit 1
+      else
+         echo "NOTE: Connect succeeded, database is working."
+         echo "*** Checking for plpgsql support ***"
+         su postgres -c 'createlang -l fossology' |grep -q plpgsql
+         if [ $? = 0 ]; then
+            echo "NOTE: plpgsql already exists in fossology database, good"
+         else
+            echo "NOTE: plpgsql doesn't exist, adding"
+            su postgres -c 'createlang plpgsql fossology'
+            if [ $? != 0 ]; then
+               echo "ERROR: failed to add plpgsql to fossology database"
+            fi
          fi
       fi
+   else
+      echo "*** Initializing database ***"
+      su postgres -c "psql < {$AGENTTESTDDIR}/fossologyinit.sql"
+      if [ $? != 0 ] ; then
+         echo "ERROR: Database failed during configuration.\n"
+         exit 1
+      fi
    fi
-else
-   echo "*** Initializing database ***"
-   su postgres -c "psql < {$AGENTTESTDDIR}/fossologyinit.sql"
-  if [ $? != 0 ] ; then
-    echo "ERROR: Database failed during configuration.\n"
-    exit 1
-  fi
-fi
 
 fi # end of DATABASE
 
@@ -285,20 +285,15 @@ fi # end of SCHEDULERONLY
 ########################################################################
 
 if [ $WEBONLY ]; then
-echo "*** Setting up the web interface ***"
+   echo "*** Setting up the web interface ***"
 
-# See if web server user (www-data) exists, if so add to the group.
-grep -q "^www-data:" /etc/passwd
-if [ $? == 0 ] ; then
-  echo "NOTE: Adding user www-data to group {$PROJECTGROUP}"
-  # this is smart enough to not add multiple times so it's ok to repeat
-  usermod -G {$PROJECTGROUP} -a www-data
-fi
-
-# touch the ui init semaphore
-INIT={$WEBDIR}/init.ui
-touch $INIT
-chown {$PROJECTUSER}:{$PROJECTGROUP} $INIT
+   # See if web server user (www-data) exists, if so add to the group.
+   grep -q "^www-data:" /etc/passwd
+   if [ $? == 0 ] ; then
+     echo "NOTE: Adding user www-data to group {$PROJECTGROUP}"
+     # this is smart enough to not add multiple times so it's ok to repeat
+     usermod -G {$PROJECTGROUP} -a www-data
+   fi
 
 fi # end of WEBONLY
 
