check for plpgsql and add it if needed
git-svn-id: http://svn.code.sf.net/p/fossology/code/trunk@1550 a5643f74-2041-0410-a2b9-94ffef304a07

diff --git a/fossology/common/fo-postinstall.in b/fossology/common/fo-postinstall.in
--- a/fossology/common/fo-postinstall.in
+++ b/fossology/common/fo-postinstall.in
@@ -150,6 +150,17 @@ if [ $? = 0 ]; then
       exit 1
    else
       echo "NOTE: Connect succeeded, database is working."
+      echo "*** Checking for plpgsql support ***"
+      su postgres -c 'createlang -l fossology' |grep plpgsql
+      if [ $? = 0 ]; then
+         echo "NOTE: plpgsql already exists in fossology database, good"
+      else
+         echo "NOTE: plpgsql doesn't exist, adding"
+         su postgres -c 'createlang plpgsql fossology'
+         if [ $? != 0 ]; then
+            echo "ERROR: failed to add plpgsql to fossology database"
+         fi
+      fi
    fi
 else
    echo "*** Initializing database ***"
