move default Db.conf creation from postinst to common/, add postinstall (db) check that postgres is running
git-svn-id: http://svn.code.sf.net/p/fossology/code/trunk@1507 a5643f74-2041-0410-a2b9-94ffef304a07

diff --git a/fossology/common/fo-postinstall.in b/fossology/common/fo-postinstall.in
--- a/fossology/common/fo-postinstall.in
+++ b/fossology/common/fo-postinstall.in
@@ -129,18 +129,16 @@ echo "*** Setting up database ***"
 
 DBCONF="{$SYSCONFDIR}/fossology/Db.conf"
 
-if [ ! -f "$DBCONF" -o "$OVERWRITE" ] ; then
-   echo "NOTE: using default version for $DBCONF"
-   echo "dbname={$PROJECT};" > "$DBCONF"
-   echo "host=localhost;" >> "$DBCONF"  # assume DB is local
-   echo "user={$PROJECTUSER};" >> "$DBCONF"
-   echo "password={$PROJECTUSER};" >> "$DBCONF"  # user WILL want to change this
-else
-  echo "WARNING: $DBCONF already exists."
-  echo "  Not overwriting, consider checking it by hand or use the OVERWRITE option." 
+# At some point this is where we could dynamically set the db password
+
+# first check that postgres is running
+su postgres -c 'echo \\q|psql'
+if [ $? != 0 ]; then
+   echo "ERROR: postgresql isn't running"
+   exit 1
 fi
 
-# first check to see if the db already exists
+# then check to see if the db already exists
 su postgres -c 'psql -l' |grep -q fossology
 if [ $? = 0 ]; then
    echo "NOTE: fossology database already exists, not creating"
