Initial commit of debian v2.0 package defination: 1. brief instruction is packaging/debian/notes; 2. some parts need discuss with team, will send email later.
git-svn-id: http://svn.code.sf.net/p/fossology/code/branches/fossology2.0/fossology@5139 a5643f74-2041-0410-a2b9-94ffef304a07

diff --git a/packaging/debian/fossology-scheduler.postrm b/packaging/debian/fossology-scheduler.postrm
--- a/packaging/debian/fossology-scheduler.postrm
+++ b/packaging/debian/fossology-scheduler.postrm
@@ -23,9 +23,9 @@ case "$1" in
     purge)
         # Scheduler.conf is dynamically generated by mkschedconf at
         # runtime so we have to clean it up by hand
-	if [ -f /etc/fossology/Scheduler.conf ]; then
-           rm -f /etc/fossology/Scheduler.conf || echo "ERROR: could not remove /etc/fossology/Scheduler.conf"
-	fi
+	#if [ -f /etc/fossology/Scheduler.conf ]; then
+        #   rm -f /etc/fossology/Scheduler.conf || echo "ERROR: could not remove /etc/fossology/Scheduler.conf"
+	#fi
 
 	# cleanup logs
 	if [ -e /var/log/fossology ]; then
