cleanup log files, test before removing, print errors instead of failing
git-svn-id: http://svn.code.sf.net/p/fossology/code/trunk/fossology@1733 a5643f74-2041-0410-a2b9-94ffef304a07

diff --git a/debian/fossology-scheduler-single.postrm b/debian/fossology-scheduler-single.postrm
--- a/debian/fossology-scheduler-single.postrm
+++ b/debian/fossology-scheduler-single.postrm
@@ -23,7 +23,14 @@ case "$1" in
     purge)
         # Scheduler.conf is dynamically generated by mkschedconf at
         # runtime so we have to clean it up by hand
-        rm -f /etc/fossology/Scheduler.conf
+	if [ -f /etc/fossology/Scheduler.conf ]; then
+           rm -f /etc/fossology/Scheduler.conf || echo "ERROR: could not remove /etc/fossology/Scheduler.conf"
+	fi
+
+	# cleanup logs
+	if [ -e /var/log/fossology ]; then
+	   rm -rf /var/log/fossology || echo "ERROR: could not remove /var/log/fossology"
+	fi
     ;;
 
     remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
