ignore scheduler return code when stopping
git-svn-id: http://svn.code.sf.net/p/fossology/code/trunk@1588 a5643f74-2041-0410-a2b9-94ffef304a07

diff --git a/fossology/scheduler/defconf/init.d/fossology.in b/fossology/scheduler/defconf/init.d/fossology.in
--- a/fossology/scheduler/defconf/init.d/fossology.in
+++ b/fossology/scheduler/defconf/init.d/fossology.in
@@ -37,7 +37,8 @@ case "$1" in
 	;;
   stop)
 	echo -n "Stopping $DESC: "
-	$DAEMON -k
+	# we don't really care about the exit code as long as it's stopped
+	$DAEMON -k || true
 	echo "$NAME."
 	;;
   #reload)
