if RepPath.conf doesn't exist print an error and exit
git-svn-id: http://svn.code.sf.net/p/fossology/code/trunk/fossology@1551 a5643f74-2041-0410-a2b9-94ffef304a07

diff --git a/common/fo-postinstall.in b/common/fo-postinstall.in
--- a/common/fo-postinstall.in
+++ b/common/fo-postinstall.in
@@ -64,6 +64,9 @@ fi
 # get path to repo
 if [ -e "{$SYSCONFDIR}/fossology/RepPath.conf" ] ; then
    REPO=`cat {$SYSCONFDIR}/fossology/RepPath.conf`
+else
+   echo "ERROR: Cannot find {$SYSCONFDIR}/fossology/RepPath.conf"
+   exit 1
 fi
 
 ## create user and group
