more database work done, checkpoint for testing purposes
git-svn-id: http://svn.code.sf.net/p/fossology/code/branches/new-build-system@1096 a5643f74-2041-0410-a2b9-94ffef304a07

diff --git a/common/fo-postinstall.in b/common/fo-postinstall.in
--- a/common/fo-postinstall.in
+++ b/common/fo-postinstall.in
@@ -124,73 +124,56 @@ exit 0
 if [ $DATABASE ]; then
 echo "*** Setting up database ***"
 
-DBCONF="{$SYSCONFDIR/fossology/Db.conf}"
+DBCONF="{$SYSCONFDIR}/fossology/Db.conf"
 
 if [ ! -f "$DBCONF" -o "$OVERWRITE" ] ; then
-  echo "NOTE: using default version for $DBCONF"
-    echo "dbname={$PROJECT};" > "$DBCONF"
-    echo "host=localhost;" >> "$DBCONF"  # assume DB is local
-    echo "user={$PROJECTUSER};" >> "$DBCONF"
-    echo "password={$PROJECTUSER};" >> "$DBCONF"  # user WILL want to change this
-  fi
+   echo "NOTE: using default version for $DBCONF"
+   echo "dbname={$PROJECT};" > "$DBCONF"
+   echo "host=localhost;" >> "$DBCONF"  # assume DB is local
+   echo "user={$PROJECTUSER};" >> "$DBCONF"
+   echo "password={$PROJECTUSER};" >> "$DBCONF"  # user WILL want to change this
 else
   echo "WARNING: $DBCONF already exists."
   echo "  Not overwriting, consider checking it by hand or use the OVERWRITE option." 
 fi
 
-FIXME rest unfinished
-# check if we can get to the database, if we can't but postgres seems ok
-# then create it
-
-echo "# Checking database connectivity"
-# FIXME: this needs to be rewritten
-{$AGENTTESTDDIR}/dbcheck
-if [ $? == 0 ] ; then
+# first check to see if the db already exists
+if [ `su postgres -c 'psql -l' |grep -q fossology` ]; then
+   echo "NOTE: fossology database already exists, not creating"
+   echo "*** Checking database connectivity ***"
+   # next check that we can talk to the db
+   {$AGENTTESTDDIR}/dbcheck
+   if [ $? != 0 ]; then
+      echo "ERROR: unable to connect to database, please check $DBCONF"
+      exit 1
+   else
+      echo "Connect succeeded, database is working."
+   fi
+else
+   echo "*** Initializing database ***"
   {$AGENTTESTDDIR}/dbinit {$AGENTTESTDDIR}/dbinit.sql
   if [ $? != 0 ] ; then
     echo "ERROR: Database failed during configuration.\n"
     exit 1
   fi
+fi
 
 # now that we know the database is available, (re)generate the
 # License.bsam file
 
-#FIXME ugg how are we going to do the cleanup....
+#FIXME we need to clean up old licenses but also not remove end user
+#  licenses, we need to figure out a way to solve this. for now we just
+#  won't clean up and instruct the user to do it by hand.
 # clean up licenses before recreating
 #rm -rf "AGENTDATADIR/licenses"
 
-echo "*** Adding licenses to database ***"
-# remove the old file
-rm -f {$AGENTDATADIR}/License.bsam.new 2>/dev/null
-cd {$AGENTDATADIR}/licenses; find . -type f | grep -v "\.meta" | sed -e 's@^./@@' | while read i ; do
-   echo "Processing $i"
-   if [ -f "$i.meta" ] ; then
-      {$AGENTDIR}/Filter_License -Q -O -M "$i.meta" "$i" >> {$AGENTDATADIR}/License.bsam.new
-   else
-      {$AGENTDIR}/Filter_License -Q -O "$i" >> {$AGENTDATADIR}/License.bsam.new
-   fi
-   if [ "\$?" != "0" ] ; then
-      echo "ERROR processing license."
-      exit 1
-   fi
-done
+echo "*** Generating license cache ***"
+{$AGENTDIR}/mkbsamcache
 
-# Make sure the file is valid
-{$AGENTDIR}/bsam-engine -t "{$AGENTDATADIR}/License.bsam.new"
-if [ "$?" != "0" ] ; then
-   echo "ERROR processing licenses."
-   echo "  Please remove \${AGENTDATADIR}/License.bsam.new"
-   echo "  and \${AGENTDATADIR}/License.bsam,"
-   echo "  then re-run the install"
-   exit 1
-fi
-rm -f {$AGENTDATADIR}/License.bsam 2>/dev/null
-mv {$AGENTDATADIR}/License.bsam.new {$AGENTDATADIR}/License.bsam 2>/dev/null
-
-# FIXME: is this needed?
-chown {$PROJECTUSER}:{$PROJECTGROUP} {$AGENTDATADIR}/License.bsam
-chmod 640 {$AGENTDATADIR}/License.bsam
-
+# FIXME: is this needed? the file will be generated by root and will be
+# readable, so it shouldn't be.
+#chown {$PROJECTUSER}:{$PROJECTGROUP} {$PROJECTSTATEDIR}/agents/License.bsam
+#chmod 640 {$PROJECTSTATEDIR}/agents/License.bsam
 
 ## Initialize database for all agents
 echo "# Initializing agents"
