Modified fo-postinstall to not use dbcheck and to use fossinit to check DB connectivity.  Modified fossinit to check for DB connectivity and return error code 2, so fo-postinstall can print the appropriate errors.  Removed some dead code from fossinit
git-svn-id: http://svn.code.sf.net/p/fossology/code/branches/fossology2.0/fossology@4884 a5643f74-2041-0410-a2b9-94ffef304a07

diff --git a/common/fo-postinstall.in b/common/fo-postinstall.in
--- a/common/fo-postinstall.in
+++ b/common/fo-postinstall.in
@@ -220,27 +220,16 @@ if [ $AGENT ]; then
    # the group doesn't exist until we create it above. So chgrp now
    chgrp {$PROJECTGROUP} $DBCONF || echo "ERROR: failed to chgrp $DBCONF"
 
-   # check that we can talk to the db
-   if [ -x {$LIBEXECDIR}/dbcheck ]; then
-      {$LIBEXECDIR}/dbcheck
-   else
-      echo "ERROR: no {$LIBEXECDIR}/dbcheck, have you installed?"
-      exit 1
-   fi
-   if [ $? != 0 ]; then
-      echo "ERROR: unable to connect to database, please check {$SYSCONFDIR}/fossology/Db.conf"
-      exit 1
-   else
-      echo "NOTE: Connect succeeded, database is working."
-   fi
-
-
-   ## Initialize the tables, License.bsam, and other setup done by fossinit
+   ## Check DataBase Connectivity, initialize the tables, License.bsam, and other 
+   ## setup done by fossinit
    # In multi-system installs the database machine must be installed first
    # in order for this to work on other machines.
    echo "*** Initializing database tables ***"
    {$BINDIR}/fossinit
    if [ $? != 0 ] ; then
+     if [ $? = 2 ] ; then
+       echo "ERROR: unable to connect to database, please check {$SYSCONFDIR}/Db.conf"
+     fi
      echo "ERROR: Unable to initialize."
      exit 1
    fi
