if the fossy user already exists, confirm it has a working shell
git-svn-id: http://svn.code.sf.net/p/fossology/code/trunk/fossology@1485 a5643f74-2041-0410-a2b9-94ffef304a07

diff --git a/common/fo-postinstall.in b/common/fo-postinstall.in
--- a/common/fo-postinstall.in
+++ b/common/fo-postinstall.in
@@ -92,6 +92,11 @@ fi
 
 if grep -q "^{$PROJECTUSER}:" /etc/passwd; then
    echo "NOTE: user '{$PROJECTUSER}' already exists, good."
+   USERSHELL=`grep "^{$PROJECTUSER}:" /etc/passwd |cut -d: -f 7`
+   if [ "$USERSHELL" = "/bin/false" ]; then
+      echo "ERROR: {$PROJECTUSER} shell must be a real shell"
+      exit 1
+   fi
 else
    useradd -c "{$PROJECT}" -g "{$PROJECTGROUP}" -m -s /bin/bash -d "$\{REPO%/*\}" "{$PROJECTUSER}"
    if [ "$?" != "0" ] ; then
