move a bunch of stuff to the agent section, make scheduler and web also run agent by default, but provide new options to avoid that for packaging
git-svn-id: http://svn.code.sf.net/p/fossology/code/trunk/fossology@1595 a5643f74-2041-0410-a2b9-94ffef304a07

diff --git a/common/fo-postinstall.in b/common/fo-postinstall.in
--- a/common/fo-postinstall.in
+++ b/common/fo-postinstall.in
@@ -9,7 +9,7 @@
 
 ## Options parsing and setup
 # parse options
-OPTS=`getopt -o adwseoh --long agent,database,web,scheduler,everything,overwrite,help -n 'fo-postinstall' -- "$@"`
+OPTS=`getopt -o adwseoh --long agent,database,web,web-only,scheduler,scheduler-only,everything,overwrite,help -n 'fo-postinstall' -- "$@"`
 
 if [ $? != 0 ]; then
    echo "ERROR: Bad option specified."
@@ -28,7 +28,9 @@ while true; do
       -a|--agent) AGENT=1; shift;;
       -d|--database) DATABASE=1; shift;;
       -w|--web) WEB=1; shift;;
+      --web-only) WEBONLY=1; shift;;
       -s|--scheduler) SCHEDULER=1; shift;;
+      --scheduler-only) SCHEDULERONLY=1; shift;;
       -e|--everything) EVERYTHING=1; shift;;
       -o|--overwrite) OVERWRITE=1; shift;;
       -h|--help)
@@ -40,18 +42,31 @@ while true; do
 	 echo "  -e or --everything : all actions (default)"
 	 echo "  -o or --overwrite  : overwrite config files with new versions"
 	 echo "  -h or --help       : this help text"
+         echo " Special options"
+         echo "  --web-only         : web, but exclude normal agent actions"
+         echo "  --scheduler-only   : scheduler, but exclude normal agent actions"
 	 exit;;
       --) shift; break;;
       *) echo "Error: option $1 not recognised"; exit 1;;
    esac
 done
 
+# the scheduler and web machines needs the agent stuff done too
+if [ $SCHEDULER ]; then
+   AGENT=1
+   SCHEDULERONLY=1
+fi
+if [ $WEB ]; then
+   AGENT=1
+   WEBONLY=1
+fi
+
 if [ $EVERYTHING ]; then
    echo "*** Running postinstall for everything ***"
    AGENT=1
    DATABASE=1
-   WEB=1
-   SCHEDULER=1
+   WEBONLY=1
+   SCHEDULERONLY=1
 fi
 
 # This must run as root.
@@ -60,82 +75,6 @@ if [ `id -u` != "0" ] ; then
    echo "Aborting."
    exit 1
 fi
-
-# get path to repo
-if [ -e "{$SYSCONFDIR}/fossology/RepPath.conf" ] ; then
-   REPO=`cat {$SYSCONFDIR}/fossology/RepPath.conf`
-else
-   echo "ERROR: Cannot find {$SYSCONFDIR}/fossology/RepPath.conf"
-   exit 1
-fi
-
-## create user and group
-# These are needed on all system types.
-# Because we are doing these by name, in the multi-machine install case
-# we may end up with uid/gid being different across machines. This will
-# either need to be fixed by hand or with NFSv4 you can use rpc.idmapd
-# to do uid/gid mapping. More details will be provided in the multi-machine
-# documentation.
-
-# Make sure the user and group exist, if not then create
-echo "*** Creating user and group ***"
-# check for group
-if grep -q "^{$PROJECTGROUP}:" /etc/group; then
-   echo "NOTE: group '{$PROJECTGROUP}' already exists, good."
-else
-   # use addgroup if it exists since it supports --system
-   if which addgroup; then
-      addgroup --system {$PROJECTGROUP}
-   else
-      groupadd {$PROJECTGROUP}
-   fi
-   if [ "$?" != "0" ] ; then
-      echo "ERROR: Unable to create group '{$PROJECTGROUP}'"
-      exit 1
-   else
-      echo "NOTE: group '{$PROJECTGROUP}' created"
-   fi
-fi
-
-# check for user
-if grep -q "^{$PROJECTUSER}:" /etc/passwd; then
-   echo "NOTE: user '{$PROJECTUSER}' already exists, good."
-   USERSHELL=`grep "^{$PROJECTUSER}:" /etc/passwd |cut -d: -f 7`
-   if [ "$USERSHELL" = "/bin/false" ]; then
-      echo "ERROR: {$PROJECTUSER} shell must be a real shell"
-      exit 1
-   fi
-else
-   # ensure that the full parent path of the HOME exists first
-   mkdir -p $\{REPO%/*/*\}
-   # use adduser if it exists since it supports --system
-   if which adduser; then
-      adduser --gecos "{$PROJECT}" --ingroup {$PROJECTGROUP} --system \
-        --shell /bin/bash --home "$\{REPO%/*\}" {$PROJECTUSER}
-   else
-      useradd -c "{$PROJECT}" -g {$PROJECTGROUP} -m \
-        -s /bin/bash -d "$\{REPO%/*\}" {$PROJECTUSER}
-   fi
-   if [ "$?" != "0" ] ; then
-      echo "ERROR: Unable to create user '{$PROJECTUSER}'"
-      exit 1
-   else
-      echo "NOTE: user '{$PROJECTUSER}' created"
-   fi
-fi
-
-# check for existance/ownership/permissions of needed directories
-# PROJECTSTATEDIR is needed in all machine cases
-if [ ! -d "{$PROJECTSTATEDIR}" ] ; then
-   mkdir -m 2775 -p "{$PROJECTSTATEDIR}"
-fi
-chown root:{$PROJECTGROUP} {$PROJECTSTATEDIR}
-chmod 2775 {$PROJECTSTATEDIR}
-if [ ! -d "{$PROJECTSTATEDIR}/agents" ] ; then
-   mkdir -m 2775 -p "{$PROJECTSTATEDIR}/agents"
-fi
-chown root:{$PROJECTGROUP} {$PROJECTSTATEDIR}/agents
-chmod 2775 {$PROJECTSTATEDIR}/agents
 
 ########################################################################
 
@@ -191,34 +130,88 @@ else
   fi
 fi
 
-# touch the ui init semaphore
-INIT={$WEBDIR}/init.ui
-touch $INIT
-chown {$PROJECTUSER}:{$PROJECTGROUP} $INIT
-
 fi # end of DATABASE
-
-## Initialize the tables, License.bsam, and other setup
-# This is needed (and should be safe to do) on all machine types
-# In multi-system installs the database machine must be installed first
-# in order for this to work on other machines.
-echo "*** Initializing database tables ***"
-{$BINDIR}/fossinit
-if [ $? != 0 ] ; then
-  echo "ERROR: Unable to initialize."
-  exit 1
-fi
-
 
 ########################################################################
 
-if [ $SCHEDULER ]; then
-   echo "*** Setting up scheduler ***"
+if [ $AGENT ]; then
 
-   # The repo dir is needed in all cases, but in a multi-machine install it
-   # will be nfs mounted from the machine with the scheduler, so we should
-   # really only create it if needed on the scheduler machine
-   echo "*** Making sure repo exists with right ownership and permissions ***"
+   ## get path to repo
+   if [ -e "{$SYSCONFDIR}/fossology/RepPath.conf" ] ; then
+      REPO=`cat {$SYSCONFDIR}/fossology/RepPath.conf`
+   else
+      echo "ERROR: Cannot find {$SYSCONFDIR}/fossology/RepPath.conf"
+      exit 1
+   fi
+
+   ## create user and group
+   # Because we are doing these by name, in the multi-machine install case
+   # we may end up with uid/gid being different across machines. This will
+   # either need to be fixed by hand or with NFSv4 you can use rpc.idmapd
+   # to do uid/gid mapping. More details will be provided in the multi-machine
+   # documentation.
+
+   # Make sure the user and group exist, if not then create
+   echo "*** Creating user and group ***"
+
+   # check for group
+   if grep -q "^{$PROJECTGROUP}:" /etc/group; then
+      echo "NOTE: group '{$PROJECTGROUP}' already exists, good."
+   else
+      # use addgroup if it exists since it supports --system
+      if which addgroup; then
+         addgroup --system {$PROJECTGROUP}
+      else
+         groupadd {$PROJECTGROUP}
+      fi
+      if [ "$?" != "0" ] ; then
+         echo "ERROR: Unable to create group '{$PROJECTGROUP}'"
+         exit 1
+      else
+         echo "NOTE: group '{$PROJECTGROUP}' created"
+      fi
+   fi
+
+   # check for user
+   if grep -q "^{$PROJECTUSER}:" /etc/passwd; then
+      echo "NOTE: user '{$PROJECTUSER}' already exists, good."
+      USERSHELL=`grep "^{$PROJECTUSER}:" /etc/passwd |cut -d: -f 7`
+      if [ "$USERSHELL" = "/bin/false" ]; then
+         echo "ERROR: {$PROJECTUSER} shell must be a real shell"
+         exit 1
+      fi
+   else
+      # ensure that the full parent path of the HOME exists first
+      mkdir -p $\{REPO%/*/*\}
+      # use adduser if it exists since it supports --system
+      if which adduser; then
+         adduser --gecos "{$PROJECT}" --ingroup {$PROJECTGROUP} --system \
+           --shell /bin/bash --home "$\{REPO%/*\}" {$PROJECTUSER}
+      else
+         useradd -c "{$PROJECT}" -g {$PROJECTGROUP} -m \
+           -s /bin/bash -d "$\{REPO%/*\}" {$PROJECTUSER}
+      fi
+      if [ "$?" != "0" ] ; then
+         echo "ERROR: Unable to create user '{$PROJECTUSER}'"
+         exit 1
+      else
+         echo "NOTE: user '{$PROJECTUSER}' created"
+      fi
+   fi
+
+   ## check for existance/ownership/permissions of needed directories
+   echo "*** Making sure needed dirs exist with right ownership/permissions ***"
+   if [ ! -d "{$PROJECTSTATEDIR}" ] ; then
+      mkdir -m 2775 -p "{$PROJECTSTATEDIR}"
+   fi
+   chown root:{$PROJECTGROUP} {$PROJECTSTATEDIR}
+   chmod 2775 {$PROJECTSTATEDIR}
+   if [ ! -d "{$PROJECTSTATEDIR}/agents" ] ; then
+      mkdir -m 2775 -p "{$PROJECTSTATEDIR}/agents"
+   fi
+   chown root:{$PROJECTGROUP} {$PROJECTSTATEDIR}/agents
+   chmod 2775 {$PROJECTSTATEDIR}/agents
+
    if [ ! -d "$REPO" ] ; then
       mkdir -p "$REPO"
       chown {$PROJECTUSER}:{$PROJECTGROUP} $REPO
@@ -231,19 +224,44 @@ if [ $SCHEDULER ]; then
       echo "NOTE: Repository already exists at $REPO"
    fi
 
-if [ -e "{$SYSCONFDIR}/fossology/Hosts.conf" ] ; then
-   grep -q "^localhost" {$SYSCONFDIR}/fossology/Hosts.conf
-   if [ $? == 0 ] ; then
-      if [ ! -d "$REPO/localhost" ] ; then
-         echo "NOTE: creating new $REPO/localhost directory"
-         mkdir $REPO/localhost
-         chown {$PROJECTUSER}:{$PROJECTGROUP} $REPO/localhost
-         chmod 2770 $REPO/localhost
-      else
-         echo "NOTE: $REPO/localhost directory already exists"
+   if [ -e "{$SYSCONFDIR}/fossology/Hosts.conf" ] ; then
+      # if we have a default Hosts.conf file, check if $REPO/localhost
+      # exists and if not then create it
+      grep -q "^localhost" {$SYSCONFDIR}/fossology/Hosts.conf
+      if [ $? == 0 ] ; then
+         if [ ! -d "$REPO/localhost" ] ; then
+            echo "NOTE: creating new $REPO/localhost directory"
+            mkdir $REPO/localhost
+            chown {$PROJECTUSER}:{$PROJECTGROUP} $REPO/localhost
+            chmod 2770 $REPO/localhost
+         else
+            echo "NOTE: $REPO/localhost directory already exists"
+         fi
       fi
+   else
+      # if we don't have a default Hosts.conf file then it's a
+      # multi-machine install and the end user needs to setup
+      echo "NOTE: Hosts.conf indicates a multi-machine install. Please"
+      echo "  make sure that the corresponding agents directories exist"
+      echo "  in $REPO and are {$PROJECTUSER}:{$PROJECTGROUP} and 2770."
    fi
-fi
+
+   ## Initialize the tables, License.bsam, and other setup done by fossinit
+   # In multi-system installs the database machine must be installed first
+   # in order for this to work on other machines.
+   echo "*** Initializing database tables ***"
+   {$BINDIR}/fossinit
+   if [ $? != 0 ] ; then
+     echo "ERROR: Unable to initialize."
+     exit 1
+   fi
+
+fi # end of AGENT
+
+########################################################################
+
+if [ $SCHEDULERONLY ]; then
+   echo "*** Setting up scheduler ***"
 
    # scheduler config file
    # this has to be done after the database is setup
@@ -262,11 +280,11 @@ fi
       echo "  consider checking it or recreating with mkschedconf."
    fi
 
-fi # end of SCHEDULER
+fi # end of SCHEDULERONLY
 
 ########################################################################
 
-if [ $WEB ]; then
+if [ $WEBONLY ]; then
 echo "*** Setting up the web interface ***"
 
 # See if web server user (www-data) exists, if so add to the group.
@@ -277,15 +295,14 @@ if [ $? == 0 ] ; then
   usermod -G {$PROJECTGROUP} -a www-data
 fi
 
-fi # end of WEB
+# touch the ui init semaphore
+INIT={$WEBDIR}/init.ui
+touch $INIT
+chown {$PROJECTUSER}:{$PROJECTGROUP} $INIT
+
+fi # end of WEBONLY
 
 ########################################################################
-
-if [ $AGENT ]; then
-   # nothing to do for agents yet
-   echo "*** Setting up agents ***"
-fi # end of AGENT
-
 
 echo "FOSSology postinstall complete, but sure to complete the remaining"
 echo "  steps in the INSTALL instructions."
