Build: fossinit now returns 1 on failure and fo-postinstall checks the return code.
git-svn-id: http://svn.code.sf.net/p/fossology/code/trunk/fossology@1583 a5643f74-2041-0410-a2b9-94ffef304a07

diff --git a/common/fo-postinstall.in b/common/fo-postinstall.in
--- a/common/fo-postinstall.in
+++ b/common/fo-postinstall.in
@@ -204,6 +204,10 @@ fi # end of DATABASE
 # in order for this to work on other machines.
 echo "*** Initializing database tables ***"
 {$BINDIR}/fossinit
+if [ $? != 0 ] ; then
+  echo "ERROR: Unable to initialize.\n"
+  exit 1
+fi
 
 
 ########################################################################
