initialize db, fixes
git-svn-id: http://svn.code.sf.net/p/fossology/code/branches/new-build-system@1202 a5643f74-2041-0410-a2b9-94ffef304a07

diff --git a/common/fo-postinstall.in b/common/fo-postinstall.in
--- a/common/fo-postinstall.in
+++ b/common/fo-postinstall.in
@@ -93,7 +93,7 @@ fi
 if grep -q "^{$PROJECTUSER}:" /etc/passwd; then
    echo "NOTE: user '{$PROJECTUSER}' already exists, good."
 else
-   useradd -c "{$PROJECT}" -g "{$PROJECTGROUP}" -m -s /bin/bash -d "${REPO%/*}" "{$PROJECTUSER}"
+   useradd -c "{$PROJECT}" -g "{$PROJECTGROUP}" -m -s /bin/bash -d "$\{REPO%/*\}" "{$PROJECTUSER}"
    if [ "$?" != "0" ] ; then
       echo "ERROR: Unable to create user '{$PROJECTUSER}'"
       exit 1
@@ -106,9 +106,9 @@ fi
 # PROJECTSTATEDIR is needed in all machine cases
 if [ ! -d "{$PROJECTSTATEDIR}" ] ; then
    mkdir -p "{$PROJECTSTATEDIR}"
-   chown {$PROJECTUSER}:{$PROJECTGROUP} {$PROJECTSTATEDIR}
+   chown root:{$PROJECTGROUP} {$PROJECTSTATEDIR}
    # FIXME: do we really need setgid?
-   chmod 2770 {$PROJECTSTATEDIR}
+   #chmod 2775 {$PROJECTSTATEDIR}
 fi
 
 ########################################################################
@@ -143,7 +143,7 @@ if [ `su postgres -c 'psql -l' |grep -q fossology` ]; then
    fi
 else
    echo "*** Initializing database ***"
-   psql < {$AGENTTESTDDIR}/fossologyinit.sql
+   su postgres -c "psql < {$AGENTTESTDDIR}/fossologyinit.sql"
   if [ $? != 0 ] ; then
     echo "ERROR: Database failed during configuration.\n"
     exit 1
@@ -164,6 +164,10 @@ echo "*** Initializing database tables ***"
 
 echo "*** Generating license cache ***"
 {$AGENTDIR}/mkbsamcache
+if [ $? != 0 ] ; then
+   echo "ERROR: failed to generate license cache.\n"
+   exit 1
+fi
 
 # FIXME: is this needed? the file will be generated by root and will be
 # readable, so it shouldn't be.
@@ -194,14 +198,14 @@ if [ $SCHEDULER ]; then
    # BTW- mkschedconf seems to be hardcoded to use localhost, if that
    # is ever fixed this code might need to be too
    SCHEDCONF={$SYSCONFDIR}/fossology/Scheduler.conf
-   if [ ! -f "{$SCHEDCONF}" -o "$OVERWRITE" ] ; then
-      mkdir -p `dirname {$SCHEDCONF}`
-      {$LIBEXECDIR}/mkschedconf -o {$SCHEDCONF} -L
-      echo "NOTE: default {$SCHEDCONF} created."
+   if [ ! -f "$SCHEDCONF" -o "$OVERWRITE" ] ; then
+      mkdir -p `dirname $SCHEDCONF`
+      {$LIBEXECDIR}/mkschedconf -o $SCHEDCONF -L
+      echo "NOTE: default $SCHEDCONF created."
       echo "  Please check that is it correct for your environment or"
       echo "  create a different one with mkschedconf."
    else
-      echo "WARNING: {$SCHEDCONF} already exists,"
+      echo "WARNING: $SCHEDCONF already exists,"
       echo "  consider checking it or recreating with mkschedconf."
    fi
 
