first attempt at Fedora/RHEL support in INSTALL and installfodeps, not tested
git-svn-id: http://svn.code.sf.net/p/fossology/code/branches/new-build-system@1394 a5643f74-2041-0410-a2b9-94ffef304a07

diff --git a/utils/installfodeps b/utils/installfodeps
--- a/utils/installfodeps
+++ b/utils/installfodeps
@@ -43,17 +43,17 @@ while true; do
    esac
 done
 
-if [ $EVERYTHING ]; then
-   echo "*** Installing both runtime and buildtime dependencies ***"
-   RUNTIME=1
-   BUILDTIME=1
-fi
-
 # This must run as root.
 if [ `id -u` != "0" ] ; then
    echo "ERROR: installfodeps must run as root."
    echo "Aborting."
    #exit 1
+fi
+
+if [ $EVERYTHING ]; then
+   echo "*** Installing both runtime and buildtime dependencies ***"
+   RUNTIME=1
+   BUILDTIME=1
 fi
 
 # figure out what distro we're on
@@ -78,10 +78,22 @@ if [ $BUILDTIME ]; then
             etch) apt-get install postgresql-server-dev-8.1;;
             lenny) apt-get install postgresql-server-dev-8.3;;
             sid) apt-get install postgresql-server-dev-8.3;;
+            *) echo "ERROR: Unknown or Unsupported Debian release"; exit 1;;
          esac
          ;;
       Fedora)
-         echo "Congrats, you get to fix this for Fedora!";
+         echo "Installing Fedora buildtime dependencies";
+         # F8=Werwolf F9=Sulphur F10=Cambridge dev=Rawhide;
+         yum install \
+            postgresql-devel \
+            file-libs libxml2 libextractor-devel \
+         ;;
+      RHEL)
+         echo "Installing RHEL buildtime dependencies";
+         yum install \
+            postgresql-devel \
+            file-libs libxml2 \
+            perl-Text-Template subversion;
          ;;
       *) echo "ERROR: distro not recognised, please fix and send a patch"; exit 1;;
    esac
@@ -106,8 +118,36 @@ if [ $RUNTIME ]; then
          esac
          ;;
       Fedora)
-         echo "Congrats, you get to fix this for Fedora!";
+         echo "Installing Fedora runtime dependencies";
+         yum install \
+            postgresql postgresql-server \
+            httpd \
+            php php-pear php-pgsql \
+            file-libs libxml2 libextractor libextractor-plugins-base \
+            binutils bzip2 cabextract cpio genisoimage poppler-utils \
+               rpm tar upx unzip gzip;
+         # F8=Werwolf F9=Sulphur F10=Cambridge dev=Rawhide;
+         case "$CODENAME" in
+            Werwolf|Sulphur)
+               echo "NOTE: sleuthkit and unrar is not available in Fedora release $CODENAME,";
+               echo "   please install from upstream sources.";;
+            Cambridge|Rawhide)
+               yum install sleuthkit;
+               echo "NOTE: unrar is not available in Fedora release $CODENAME,";
+               echo "   please install from upstream sources.";;
+            *) echo "ERROR: Unknown or Unsupported Fedora release"; exit 1;;
+         esac
          ;;
+      RHEL)
+         echo "Installing RHEL runtime dependencies";
+         yum install \
+            postgresql postgresql-server \
+            httpd \
+            php php-pear php-pgsql \
+            file-libs libxml2 \
+            binutils bzip2 cpio mkisofs poppler-utils rpm tar unzip gzip
+         echo "NOTE: libextractor, cabextract, sleuthkit, upx, and unrar are not"
+         echo "    available in RHEL please install from upstream sources.";;
       *) echo "ERROR: distro not recognised, please fix and send a patch"; exit 1;;
    esac
 fi
