fix(uuid-ossp): Create extension as postgres
The code to create uuid-ossp extension works under fossology user. Add
the extension creation to code sections which works as postgres user.

Signed-off-by: Gaurav Mishra <mishra.gaurav@siemens.com>

diff --git a/src/testing/utils/dbcreate b/src/testing/utils/dbcreate
--- a/src/testing/utils/dbcreate
+++ b/src/testing/utils/dbcreate
@@ -31,6 +31,17 @@ if [ $? = 0 ]; then
          echo "ERROR: failed to add plpgsql to fosstest database"
       fi
    fi
+   echo "*** Checking for 'uuid-ossp' support ***"
+   su postgres -c 'echo "SELECT * FROM pg_extension;" | psql -t fosstest' |grep -q uuid-ossp
+   if [ $? = 0 ]; then
+      echo "NOTE: 'uuid-ossp' already exists in fossology database, good"
+   else
+      echo "NOTE: 'uuid-ossp' doesn't exist, adding"
+      su postgres -c 'echo "CREATE EXTENSION \"uuid-ossp\";" | psql fosstest'
+      if [ $? != 0 ]; then
+         echo "ERROR: failed to add 'uuid-ossp' to fossology database"
+      fi
+   fi
 else
    echo "*** Initializing database ***"
    su postgres -c "psql < testDBinit.sql"
