Fixed bug4731, some directory didn't be removed when use purge package.
git-svn-id: http://svn.code.sf.net/p/fossology/code/trunk/fossology@6883 a5643f74-2041-0410-a2b9-94ffef304a07

diff --git a/packaging/deb/fossology-common.postrm b/packaging/deb/fossology-common.postrm
--- a/packaging/deb/fossology-common.postrm
+++ b/packaging/deb/fossology-common.postrm
@@ -26,10 +26,18 @@ case "$1" in
        echo "removing FOSSology user..."
        deluser --system fossy || true
        echo "removing FOSSology group..."
-       delgroup --system fossy || true
-       # we can't remove the repo because we can't know if that's what
-       # the user wants
-       echo "NOTE: Not removing the FOSSology repository, please clean up by hand"
+       delgroup fossy || true
+       # purge will remove the repository directory
+       echo "removing the FOSSology repository..."
+       if [ -d /srv/fossology/repository ]; then
+         rm -rf /srv/fossology
+         if [ $? != 0 ]; then
+           echo "ERROR: failed to delete repository"
+           exit 1
+         fi
+       else
+        echo "NOTE: repository does not exist, so not deleting"
+       fi
     ;;
 
     remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
