bug(fix error) Modified each mentioned file support for MacOs & Windows Subsystem for Linux.

diff --git a/src/delagent/mod_deps b/src/delagent/mod_deps
--- a/src/delagent/mod_deps
+++ b/src/delagent/mod_deps
@@ -5,6 +5,51 @@
 # SPDX-FileCopyrightText: © 2011-2012 Hewlett-Packard Development Company, L.P.
 
 # SPDX-License-Identifier: GPL-2.0-only
+# Installing Package Manager for different Enviornment  
+required_utils=("dos2unix")
+
+for util in "${required_utils[@]}"; do
+    if ! command -v $util &> /dev/null; then
+        echo "$util is not installed. Attempting to install..."
+        if [[ $EUID -ne 0 ]]; then
+            echo "Unable to install $util Aborting..."
+            exit 1
+        else
+            case $DISTRO in
+                Linux)
+                    # Detecting Package Manager based on Enviornment
+                    if command -v apt-get &> /dev/null; then
+                        sudo apt-get install -y $util
+                    elif command -v yum &> /dev/null; then
+                        sudo yum install -y $util
+                    elif command -v dnf &> /dev/null; then
+                        sudo dnf install -y $util
+                    elif command -v pacman &> /dev/null; then
+                        sudo pacman -S --noconfirm $util
+                    else
+                        echo "No compatible package manager found. Aborting..."
+                        exit 1
+                    fi
+                    ;;
+                Darwin)
+                    if command -v brew &> /dev/null; then
+                        brew install $util
+                    else
+                        echo "Homebrew is not installed. Please install Homebrew to proceed."
+                        exit 1
+                    fi
+                    ;;
+                *)
+                    echo "Unsupported OS."
+                    exit 1
+                    ;;
+            esac
+        fi
+    fi
+done
+
+# Line Encoding
+find . -type f -print0 | parallel -0 'grep -Iql $'\r'' {} && dos2unix {}'
 
 source "$(dirname ${BASH_SOURCE[0]})/../../utils/utils.sh"
 
@@ -57,13 +102,19 @@ if [[ $EVERYTHING ]]; then
 fi
 
 # figure out what distro we're on
-DISTRO=$(lsb_release --id --short)
+DISTRO=$(uname -s || lsb_release --id --short)
+CODENAME=$(sw_vers -productVersion 2>/dev/null || lsb_release --codename --short 2>/dev/null)
+ARCH=$(uname -m) 
+
 
 ########################################################################
 
 if [[ $BUILDTIME ]]; then
   echo "*** Installing $DISTRO buildtime dependencies ***";
   case "$DISTRO" in
+    Darwin)
+      brew install libgcrypt
+      ;;
     Debian|Ubuntu)
       apt-get $YesOpt install \
         libgcrypt20-dev libcrypt-dev
@@ -78,6 +129,8 @@ fi
 if [[ $RUNTIME ]]; then
   echo "*** Installing $DISTRO runtime dependencies ***";
   case "$DISTRO" in
+    Darwin)
+      brew install libgcrypt
     Debian|Ubuntu)
       apt-get $YesOpt install \
         libgcrypt20 libcrypt1
diff --git a/utils/fo-installdeps b/utils/fo-installdeps
--- a/utils/fo-installdeps
+++ b/utils/fo-installdeps
@@ -12,8 +12,9 @@
 # canonical location for such info, then fix it there first and also
 # update this file and the INSTALL document.
 
-# Line Encoding 
-required_utils=("curl" "dos2unix")
+# Installing Package Manager for different Enviornment  
+required_utils=("dos2unix")
+
 for util in "${required_utils[@]}"; do
     if ! command -v $util &> /dev/null; then
         echo "$util is not installed. Attempting to install..."
@@ -21,18 +22,41 @@ for util in "${required_utils[@]}"; do
             echo "Unable to install $util Aborting..."
             exit 1
         else
-            case $(uname) in
-                Linux) apt-get install -y $util ;;
-                Darwin) brew install $util ;;
-                *) echo "Unsuported OS." ; exit 1 ;;
+            case $DISTRO in
+                Linux)
+                    # Detecting Package Manager based on Enviornment
+                    if command -v apt-get &> /dev/null; then
+                        sudo apt-get install -y $util
+                    elif command -v yum &> /dev/null; then
+                        sudo yum install -y $util
+                    elif command -v dnf &> /dev/null; then
+                        sudo dnf install -y $util
+                    elif command -v pacman &> /dev/null; then
+                        sudo pacman -S --noconfirm $util
+                    else
+                        echo "No compatible package manager found. Aborting..."
+                        exit 1
+                    fi
+                    ;;
+                Darwin)
+                    if command -v brew &> /dev/null; then
+                        brew install $util
+                    else
+                        echo "Homebrew is not installed. Please install Homebrew to proceed."
+                        exit 1
+                    fi
+                    ;;
+                *)
+                    echo "Unsupported OS."
+                    exit 1
+                    ;;
             esac
         fi
     fi
 done
 
-if grep -qEi "(Microsoft|WSL)" /proc/version; then
-    find . -type f -print0 | xargs -0 dos2unix
-fi
+# Line Encoding
+find . -type f -print0 | parallel -0 'grep -Iql $'\r'' {} && dos2unix {}'
 
 show_help() {
   cat <<EOF
@@ -100,226 +124,49 @@ if [[ $EVERYTHING ]]; then
 fi
 
 # figure out what distro we're on
-DISTRO=$(lsb_release --id --short)
-CODENAME=$(lsb_release --codename --short)
+DISTRO=$(uname -s || lsb_release --id --short)
+CODENAME=$(sw_vers -productVersion 2>/dev/null || lsb_release --codename --short 2>/dev/null)
+ARCH=$(uname -m) 
 
 ########################################################################
 
 echo "install core dependencies"
 
-# Darwin
-if [[ $BUILDTIME && "$(uname)" == "Darwin" ]]; then
-   echo "*** Installing buildtime dependencies ***";
-   brew install curl libxml2 icu4c cmake ninja boost postgresql composer
-   brew install mxml cunit libmagic glib libpq cppunit
-
-   case "$CODENAME" in
-       stretch|buster|bullseye|bookworm|sid|focal|jammy)
-           brew install php@7.4
-           brew link --force php@7.4
-           ;;
-       *)
-           echo "ERROR: Unsupported $CODENAME for macOS. Please check available versions."
-           exit 1
-           ;;
-   esac
-
-   # Check if PostgreSQL development headers are needed
-   if ! brew list | grep -q postgresql; then
-       brew install postgresql
-   fi
-
-fi
-
-# wsl & linux 
 if [[ $BUILDTIME ]]; then
-   echo "*** Installing $DISTRO buildtime dependencies ***";
-   case "$DISTRO" in
-      Debian|Ubuntu)
-         echo "DB: Installing build essential....."
-         apt-get $YesOpt install \
-            libmxml-dev curl libxml2-dev libcunit1-dev libicu-dev \
-            build-essential libtext-template-perl subversion rpm librpm-dev \
-            libmagic-dev libglib2.0 libboost-regex-dev libzstd-dev \
-            libboost-program-options-dev libpq-dev composer patch devscripts \
-            libdistro-info-perl libcppunit-dev libomp-dev cmake ninja-build
-         case "$CODENAME" in
-           stretch)
-             apt-get $YesOpt install php-mbstring php7.0-cli php7.0-xml php7.0-zip php7.0-gd php7.0-pgsql php7.0-curl php7.0-uuid php7.0-sqlite3;;
-           buster)
-             apt-get $YesOpt install php-mbstring php7.3-cli php7.3-xml php7.3-zip php7.3-gd php7.3-pgsql php7.3-curl php7.3-uuid php7.3-sqlite3;;
-           bullseye)
-             apt-get $YesOpt install php7.4-mbstring php7.4-cli php7.4-xml php7.4-zip php7.4-gd php7.4-pgsql php7.4-curl php7.4-uuid php7.4-sqlite3;;
-           bookworm)
-             apt-get $YesOpt install php8.2-mbstring php8.2-cli php8.2-xml php8.2-zip php8.2-gd php8.2-pgsql php8.2-curl php8.2-uuid php8.2-sqlite3;;
-           sid)
-             apt-get $YesOpt install php-mbstring php-cli php-xml php-zip php-gd php-pgsql php-curl php-uuid php-sqlite3;;
-           focal)
-             apt-get $YesOpt install php-mbstring php-cli php-xml php-zip php-gd php-pgsql php-curl php-uuid php-sqlite3;;
-           jammy)
-             apt-get $YesOpt install php-mbstring php-cli php-xml php-zip php-gd php-pgsql php-curl php-uuid php-sqlite3;;
-         esac
-         if ! dpkg --get-selections | grep -q postgresql-server-dev; then  ## if postgresql-server-dev is not installed
-           case "$CODENAME" in
-              stretch)
-                apt-get $YesOpt install postgresql-server-dev-9.6;;
-              buster)
-                apt-get $YesOpt install postgresql-server-dev-11;;
-              bullseye)
-                apt-get $YesOpt install postgresql-server-dev-13;;
-              bookworm)
-                apt-get $YesOpt install postgresql-server-dev-15;;
-              sid)
-                apt-get $YesOpt install postgresql-server-dev-16;;
-              focal)
-                apt-get $YesOpt install postgresql-server-dev-12;;
-              jammy)
-                apt-get $YesOpt install postgresql-server-dev-14;;
-              *) echo "ERROR: Unknown or Unsupported $DISTRO $CODENAME release, please report to the mailing list"; exit 1;;
-           esac
-         fi
-         ;;
-      Fedora)
-         yum $YesOpt groupinstall "Development Tools"
-         yum $YesOpt install \
-            perl-Text-Template subversion \
-            postgresql-devel file-devel \
-            libxml2 \
-            boost-devel php-mbstring libicu-devel libpq-devel patch \
-            libomp-devel cmake ninja-build
-         ;;
-      RedHatEnterprise*|CentOS)
-         yum $YesOpt install \
-            postgresql-devel \
-            gcc make file libxml2 \
-            perl-Text-Template subversion \
-            boost-devel php-mbstring libicu-devel libpq-devel patch \
-            libomp-devel cmake ninja-build
-         ;;
-      *) echo "ERROR: distro not recognised, please fix and send a patch"; exit 1;;
-   esac
-fi
+    case "$DISTRO" in
+        Darwin)
+            echo "*** Installing buildtime dependencies for macOS ***"
+            brew install curl libxml2 icu4c cmake ninja boost postgresql composer
+            brew install mxml cunit libmagic glib libpq cppunit
+            brew install php
 
-########################################################################
-
-# Darwin
-if [[ $RUNTIME && "$(uname)" == "Darwin" ]]; then
-    echo "*** Installing runtime dependencies ***"
-    # Basic Homebrew installations
-    brew install httpd php@7.4 postgresql libxml2 p7zip wget git svn unrar libboost
-
-    case "$CODENAME" in
-        stretch|buster|bullseye|bookworm|sid|focal|jammy)
-            # PHP version mapping
-            brew install php@7.4
-            brew link --force php@7.4
+            if ! brew list | grep -q postgresql; then
+                brew install postgresql
+            fi
             ;;
-        *)
-            echo "ERROR: Unsupported $CODENAME for macOS. Please check available versions."
+       Debian|Ubuntu)
+            echo "*** Installing buildtime dependencies for Linux $DISTRO ***"
+            apt-get $YesOpt install \
+             libmxml-dev curl libxml2-dev libcunit1-dev libicu-dev \
+             build-essential libtext-template-perl subversion rpm librpm-dev \
+             libmagic-dev libglib2.0 libboost-regex-dev libzstd-dev \
+             libboost-program-options-dev libpq-dev composer patch devscripts \
+             libdistro-info-perl libcppunit-dev libomp-dev cmake ninja-build
+            ;;
+         RedHatEnterprise*|CentOS|Fedora)
+         echo "*** Installing buildtime dependencies for Linux $DISTRO ***"
+            yum $YesOpt install \
+              libmxml-dev curl libxml2-dev libcunit1-dev libicu-dev \
+              build-essential libtext-template-perl subversion rpm librpm-dev \
+              libmagic-dev libglib2.0 libboost-regex-dev libzstd-dev \
+              libboost-program-options-dev libpq-dev composer patch devscripts \
+              libdistro-info-perl libcppunit-dev libomp-dev cmake ninja-build
+            ;;
+          *)
+            echo "ERROR: Unsupported operating system $DISTRO. Exiting installation."
             exit 1
             ;;
     esac
-
-    # Service management 
-    brew services start httpd
-    brew services start postgresql
-
-    # Optional: Install Mail Transport Agent for email notifications
-    echo "*** Try 'brew install msmtp' or another preferred MTA ***"
-
-fi
-
-# wsl & linux 
-if [[ $RUNTIME ]]; then
-   echo "*** Installing $DISTRO runtime dependencies ***";
-   echo "*** For optional email notifications a Mail Transport Agent Must be ***";
-   echo "*** installed. Consult with your system administrator. Or try ***";
-   echo "*** apt-get install mail-transport-agent, pick one and install it***";
-   case "$DISTRO" in
-      Debian|Ubuntu)
-        echo "doing runtime"
-         apt-get $YesOpt install apache2
-         apt-get $YesOpt install php-pear \
-            libxml2 libzstd1 \
-            binutils \
-            cabextract cpio sleuthkit genisoimage \
-            poppler-utils \
-            unrar-free unzip p7zip-full p7zip wget \
-            subversion git \
-            dpkg-dev php-uuid
-         case "$CODENAME" in
-            stretch)
-               apt-get $YesOpt install postgresql-9.6 php7.0 php7.0-pgsql libapache2-mod-php7.0 php7.0-pgsql \
-                 php7.0-cli php7.0-curl php7.0-xml php7.0-zip php7.0-mbstring php7.0-uuid php-gettext s-nail libboost-program-options1.62.0 \
-                 libboost-regex1.62.0 libicu57;;
-            buster)
-               apt-get $YesOpt install postgresql-11 php7.3 php7.3-pgsql libapache2-mod-php7.3 php7.3-pgsql \
-                 php7.3-cli php7.3-curl php7.3-xml php7.3-zip php7.3-mbstring php7.3-uuid php-gettext s-nail libboost-program-options1.67.0 \
-                 libboost-regex1.67.0 libicu63;;
-            bullseye)
-               apt-get $YesOpt install postgresql-13 php7.4 php7.4-pgsql \
-               libapache2-mod-php7.4 php7.4-pgsql php7.4-cli php7.4-curl \
-               php7.4-xml php7.4-zip php7.4-mbstring php7.4-uuid php-php-gettext s-nail \
-               libboost-program-options1.74.0 libboost-regex1.74.0 libicu67;;
-            bookworm)
-               apt-get $YesOpt install postgresql-15 php8.2 php8.2-pgsql \
-               libapache2-mod-php8.2 php8.2-pgsql php8.2-cli php8.2-curl \
-               php8.2-xml php8.2-zip php8.2-mbstring php8.2-uuid php-php-gettext s-nail \
-               libboost-program-options1.74.0 libboost-regex1.74.0 libicu72;;
-            sid)
-               apt-get $YesOpt install postgresql php php-pgsql php-cli php-curl php-xml php-zip php-mbstring php-uuid php-gettext s-nail \
-                 libboost-program-options1.74.0 libboost-regex1.74.0 libicu67;;
-            focal)
-               apt-get $YesOpt install postgresql php php-pgsql php-cli php-curl php-xml php-zip php-mbstring php-uuid s-nail \
-                 libboost-program-options1.71.0 libboost-regex1.71.0 libicu66;;
-            jammy)
-               apt-get $YesOpt install postgresql-14 php8.1 php8.1-pgsql \
-               libapache2-mod-php8.1 php8.1-pgsql php8.1-cli php8.1-curl \
-               php8.1-xml php8.1-zip php8.1-mbstring php8.1-uuid php-php-gettext s-nail \
-               libboost-program-options1.74.0 libboost-regex1.74.0 libicu70;;
-            *) echo "ERROR: Unknown or Unsupported $DISTRO $CODENAME release, please report to the mailing list"; exit 1;;
-         esac
-         ;;
-      Fedora)
-         yum $YesOpt install postgresql-server httpd chkconfig
-         yum $YesOpt install \
-            postgresql \
-            php php-pear php-pgsql php-process php-xml php-mbstring\
-            smtpdaemon \
-            libxml2 \
-            binutils mailx \
-            sleuthkit boost libicu
-
-         # enable, possible init, and start postgresql
-         /sbin/chkconfig postgresql on
-         if [ ! -f /var/lib/pgsql/data/PG_VERSION ]; then
-            /usr/bin/postgresql-setup --initdb
-         fi
-         /usr/bin/systemctl start postgresql
-
-         echo "NOTE: unrar is not available in Fedora release $CODENAME,"
-         echo "   please install from upstream sources."
-         ;;
-      RedHatEnterprise*|CentOS)
-         yum $YesOpt install postgresql-server httpd
-         yum $YesOpt install \
-            postgresql \
-            php php-pear php-pgsql php-process php-mbstring\
-            smtpdaemon \
-            file libxml2 \
-            binutils mailx boost libicu
-         echo "NOTE: cabextract, sleuthkit, upx, and unrar are not"
-         echo "    available in RHEL please install from upstream sources."
-         ;;
-      *) echo "ERROR: distro not recognised, please fix and send a patch"; exit 1;;
-   esac
-
-   if [[ $OFFLINE ]]; then
-       echo "WARNING: composer is not installed, and the installer does not install it due to the offline switch"
-       echo "Please run the equivalent of 'sudo ./utils/install_composer.sh'"
-   else
-       "$( dirname "$0" )/install_composer.sh"
-   fi
 fi
 
 ########################################################################
