create needed dir, add some error checking
git-svn-id: http://svn.code.sf.net/p/fossology/code/branches/new-build-system@1201 a5643f74-2041-0410-a2b9-94ffef304a07

diff --git a/agents/foss_license_agent/Licenses/mkbsamcache.in b/agents/foss_license_agent/Licenses/mkbsamcache.in
--- a/agents/foss_license_agent/Licenses/mkbsamcache.in
+++ b/agents/foss_license_agent/Licenses/mkbsamcache.in
@@ -7,18 +7,27 @@ if [ -f "{$PROJECTSTATEDIR}/agents/License.bsam.new" ]; then
    rm -f {$PROJECTSTATEDIR}/agents/License.bsam.new
 fi
 
+if [ ! -d "{$PROJECTSTATEDIR}/agents/" ]; then
+   mkdir -p "{$PROJECTSTATEDIR}/agents/"
+fi
+
 # Create cached files
 cd {$AGENTDATADIR}/licenses/
+
 find . -type f | sed -e 's@^./@@' | grep -v \.meta | sort | while read i ; do
    echo "Processing $i"
    if [ -f "$i.meta" ] ; then
       {$AGENTDIR}/Filter_License -Q -O -M "$i.meta" "$i" >> {$PROJECTSTATEDIR}/agents/License.bsam.new
+      if [ $? != 0 ] ; then
+         echo "ERROR processing $i."
+         exit 1
+      fi
    else
       {$AGENTDIR}/Filter_License -Q -O "$i" >> {$PROJECTSTATEDIR}/agents/License.bsam.new
-   fi
-   if [ "$?" != "0" ] ; then
-      echo "ERROR processing license."
-      exit 1
+      if [ $? != 0 ] ; then
+         echo "ERROR processing $i."
+         exit 1
+      fi
    fi
 done
 
