update for bugs within new scheduler and changes to the new fossology library to get it to correctly compile.
git-svn-id: http://svn.code.sf.net/p/fossology/code/branches/fossology2.0/fossology@4030 a5643f74-2041-0410-a2b9-94ffef304a07

diff --git a/scheduler/defconf/init.d/fossology.in b/scheduler/defconf/init.d/fossology.in
--- a/scheduler/defconf/init.d/fossology.in
+++ b/scheduler/defconf/init.d/fossology.in
@@ -16,7 +16,8 @@
 ### END INIT INFO
 
 PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
-DAEMON={$LIBEXECDIR}/fossology-scheduler
+DAEMON_V1={$LIBEXECDIR}/fossology-scheduler
+DAEMON_V2={$LIBEXECDIR}/fo_scheduler
 WATCHDOG={$LIBEXECDIR}/fo_watchdog
 NAME=scheduler
 DESC="FOSSology job scheduler"
@@ -28,11 +29,12 @@ test -x $WATCHDOG || exit 0
 ENABLED=1
 
 # Include scheduler defaults if available
-SCHEDULEROPT="-d -R" 
+SCHEDULEROPT_V1="-d -R"
+SCHEDULEROPT_V2="--daemon --reset --log={$LOGDIR}/fossology_2.log"
 if [ -f {$SYSCONFDIR}/default/fossology ] ; then
-	# This can override SCHEDULEROPT.
-	# Be sure to keep "-d" for daemon mode
-	. {$SYSCONFDIR}/default/fossology
+    # This can override SCHEDULEROPT_V1 or SCHEDULEROPT_V2.
+    # Be sure to keep "-d" for daemon mode
+    . {$SYSCONFDIR}/default/fossology
 fi
 
 # Quit quietly, if $ENABLED is 0.
@@ -42,56 +44,55 @@ set -e
 
 case "$1" in
   start)
-	echo -n "Starting $DESC: "
-	$DAEMON $SCHEDULEROPT
-	echo "$NAME."
+    echo -n "Starting $DESC: "
+    $DAEMON_V1 $SCHEDULEROPT_V1
+    $DAEMON_V2 $SCHEDULEROPT_V2
+    echo "$NAME."
     $WATCHDOG
-	;;
+    ;;
   stop)
-	echo -n "Stopping $DESC: "
-	# we don't really care about the exit code as long as it's stopped
+    echo -n "Stopping $DESC: "
+    # we don't really care about the exit code as long as it's stopped
     $WATCHDOG -k
-	$DAEMON -k || true
-	echo "$NAME."
-	;;
-  #reload)
-	#
-	#	If the daemon can reload its config files on the fly
-	#	for example by sending it SIGHUP, do it here.
-	#
-	#	If the daemon responds to changes in its config file
-	#	directly anyway, make this a do-nothing entry.
-	#
-	# echo "Reloading $DESC configuration files."
-	# start-stop-daemon --stop --signal 1 --quiet --pidfile \
-	#	/var/run/$NAME.pid --exec $DAEMON
-  #;;
+    $DAEMON_V1 -k || true
+    $DAEMON_V2 --kill || true
+    echo "$NAME."
+    ;;
+  reload)
+    # the new scheduler can reload its config files, the old one cannot
+    # a change to config for the old scheduler requires a restart
+    kill -1 `ps aux | awk '/fo_scheduler/ && !/awk/ {print $2}'`
+    ;;
   force-reload)
-	#
-	#	If the "reload" option is implemented, move the "force-reload"
-	#	option to the "reload" entry above. If not, "force-reload" is
-	#	just the same as "restart" except that it does nothing if the
-	#   daemon isn't already running.
-	# check wether $DAEMON is running. If so, restart
+    #
+    #   If the "reload" option is implemented, move the "force-reload"
+    #   option to the "reload" entry above. If not, "force-reload" is
+    #   just the same as "restart" except that it does nothing if the
+    #   daemon isn't already running.
+    # check wether $DAEMON is running. If so, restart
     $WATCHDOG -k
-	$DAEMON -k
-	$DAEMON $SCHEDULEROPT
+    $DAEMON_V1 -k
+    $DAEMON_V1 $SCHEDULEROPT_V1
+    $DAEMON_V2 --kill
+    $DAEMON_V2 $SCHEDULEROPT_V2
     $WATCHDOG
-	;;
+    ;;
   restart)
     echo -n "Restarting $DESC: "
     $WATCHDOG -k
-	$DAEMON -k
-	$DAEMON $SCHEDULEROPT
-	echo "$NAME."
+    $DAEMON_V1 -k
+    $DAEMON_V1 $SCHEDULEROPT_V1
+    $DAEMON_V2 --kill
+    $DAEMON_V2 $SCHEDULEROPT_V2
+    echo "$NAME."
     $WATCHDOG
-	;;
+    ;;
   *)
-	N={$INITDIR}/init.d/$NAME
-	# echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
-	echo "Usage: $N \{start|stop|restart|force-reload\}" >&2
-	exit 1
-	;;
+    N={$INITDIR}/init.d/$NAME
+    echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
+    #echo "Usage: $N \{start|stop|restart|force-reload\}" >&2
+    exit 1
+    ;;
 esac
 
 exit 0
